name: SFOS build

on:
  push:
    branches:
      - master
      - legacy
    tags:
      - 'release-*'
      - 'pre-*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Prepare
      run: mkdir output

    #- name: Build armv7hl legacy
    #  # id: build_armv7hl
    #  uses: coderus/github-sfos-build@master
    #  with:
    #    release: 3.4.0.22

    #- name: Rename legacy rpm
    #  run: for x in ./RPMS/*.rpm; do sudo mv "$x" "./RPMS/`basename "$x" .rpm`.legacy-sfos-3.4.rpm"; done

    - name: Build armv7hl
      id: build_armv7hl
      uses: coderus/github-sfos-build@master
      with:
        release: 4.2.0.21

    - name: Build i486
      id: build_i486
      uses: coderus/github-sfos-build@master
      with:
        release: 4.2.0.21
        arch: i486

    - name: Build aarch64
      id: build_aarch64
      uses: coderus/github-sfos-build@master
      with:
        release: 4.2.0.21
        arch: aarch64

    - name: Upload build result
      uses: actions/upload-artifact@v4.6.2
      with:
        name: github-actions-test
        path: RPMS

    - name: Create release
      if: startsWith(github.ref, 'refs/tags/release')
      uses: softprops/action-gh-release@v2
      with:
        files: RPMS/*.rpm
        generate_release_notes: true
        fail_on_unmatched_files: true

    - name: Create prerelease
      if: startsWith(github.ref, 'refs/tags/pre')
      uses: softprops/action-gh-release@v2
      with:
        files: RPMS/*.rpm
        prerelease: true
        body: This is a pre-release for testing purposes only. It may or may not be unstable.
        generate_release_notes: true
        fail_on_unmatched_files: true