name: SFOS build

on:
  push:
    branches:
      - master
      - legacy
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prepare
      run: mkdir output
#
    - name: Build armv7hl legacy
      # id: build_armv7hl
      uses: coderus/github-sfos-build@master
      with:
        release: 3.4.0.22

    - name: Rename legacy rpm
      run: for x in ./RPMS/*.rpm; do sudo mv "$x" "./RPMS/`basename "$x" .rpm`.legacy-sfos-3.4.rpm"; done

    - name: Build armv7hl
      id: build_armv7hl
      uses: coderus/github-sfos-build@master
      with:
        release: 4.2.0.21

    - name: Build i486
      id: build_i486
      uses: coderus/github-sfos-build@master
      with:
        release: 4.2.0.21
        arch: i486

    - name: Build aarch64
      id: build_aarch64
      uses: coderus/github-sfos-build@master
      with:
        release: 4.2.0.21
        arch: aarch64

    - name: Upload build result
      uses: actions/upload-artifact@v2
      with:
        name: github-actions-test
        path: RPMS

    - name: Create release
      if: contains(github.ref, 'release')
      run: |
        set -x
        assets=()
        for asset in RPMS/*.rpm; do
          assets+=("-a" "$asset")
        done
        tag_name="${GITHUB_REF##*/}"
        hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create prerelease
      if: contains(github.ref, 'pre')
      run: |
        set -x
        assets=()
        for asset in RPMS/*.rpm; do
          assets+=("-a" "$asset")
        done
        tag_name="${GITHUB_REF##*/}"
        hub release create -p "${assets[@]}" -m "$tag_name" -m "This is a pre-release for testing purposes only. It may or may not be unstable." "$tag_name"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
